using AIOMux.Core.Interfaces;
using AIOMux.Core.Models;

namespace AIOMux.Core.Builders;

/// <summary>
/// Builds an ExecutionPlan from a planner or generation service.
/// Used when a planner or LLM generates steps dynamically.
/// 
/// Example usage:
/// <code>
/// var plan = ExecutionPlanFactory.Create("DynamicPlan")
///     .WithDescription("Generated by planner service")
///     .WithMetadata("planner", "GPT-4")
///     .AddToolStep("search", "WebSearch", 
///         inputs: new() { ["query"] = "machine learning trends" })
///     .AddToolStep("summarize", "Summarizer",
///         bindings: new() { ["input"] = "state.search" },
///         outputKey: "summary")
///     .BuildAsync();
/// </code>
/// </summary>
public class PlannerExecutionPlanBuilder : IExecutionPlanBuilder
{
    private readonly string _planName;
    private readonly List<ExecutionStep> _steps = new();
    private string? _description;
    private readonly Dictionary<string, object?> _metadata = new();

    /// <summary>
    /// Creates a new builder for a generated plan.
    /// </summary>
    /// <param name="planName">Name of the plan</param>
    public PlannerExecutionPlanBuilder(string planName)
    {
        if (string.IsNullOrWhiteSpace(planName))
            throw new ArgumentException("Plan name cannot be empty", nameof(planName));

        _planName = planName;
    }

    /// <summary>
    /// Adds a tool step to the plan.
    /// </summary>
    /// <param name="stepId">Unique identifier for this step</param>
    /// <param name="toolName">Name of the tool to invoke</param>
    /// <param name="inputs">Static input values for the step</param>
    /// <param name="bindings">Bindings from context state into step inputs (e.g., "input" -> "state.previousOutput")</param>
    /// <param name="outputKey">Optional key to store the step output in state</param>
    public PlannerExecutionPlanBuilder AddToolStep(string stepId, string toolName, Dictionary<string, object?>? inputs = null, Dictionary<string, string>? bindings = null, string? outputKey = null)
    {
        _steps.Add(new ExecutionStep
        {
            Id = stepId,
            Type = "tool",
            Target = toolName,
            Inputs = inputs ?? new(),
            Bindings = bindings ?? new(),
            OutputKey = outputKey
        });
        return this;
    }

    /// <summary>
    /// Adds an agent step to the plan.
    /// </summary>
    /// <param name="stepId">Unique identifier for this step</param>
    /// <param name="agentName">Name of the agent to invoke</param>
    /// <param name="inputs">Static input values for the step</param>
    /// <param name="bindings">Bindings from context state into step inputs</param>
    /// <param name="outputKey">Optional key to store the step output in state</param>
    public PlannerExecutionPlanBuilder AddAgentStep(string stepId, string agentName, Dictionary<string, object?>? inputs = null, Dictionary<string, string>? bindings = null, string? outputKey = null)
    {
        _steps.Add(new ExecutionStep
        {
            Id = stepId,
            Type = "agent",
            Target = agentName,
            Inputs = inputs ?? new(),
            Bindings = bindings ?? new(),
            OutputKey = outputKey
        });
        return this;
    }

    /// <summary>
    /// Sets the plan description.
    /// </summary>
    public PlannerExecutionPlanBuilder WithDescription(string description)
    {
        _description = description;
        return this;
    }

    /// <summary>
    /// Adds metadata to the plan (e.g., planner service name, version).
    /// </summary>
    public PlannerExecutionPlanBuilder WithMetadata(string key, object? value)
    {
        _metadata[key] = value;
        return this;
    }

    /// <summary>
    /// Builds the ExecutionPlan from collected steps.
    /// </summary>
    public Task<ExecutionPlan> BuildAsync(CancellationToken cancellationToken = default)
    {
        if (_steps.Count == 0)
            throw new InvalidOperationException("Plan must have at least one step");

        var plan = new ExecutionPlan
        {
            Name = _planName,
            Description = _description,
            Source = PlanSource.Generated,
            Steps = _steps.AsReadOnly(),
            Metadata = new Dictionary<string, object?>(_metadata)
        };

        return Task.FromResult(plan);
    }
}
